[workspace]
resolver = "2"
members = [
    "crates/nemoir-ir",
    "crates/nemoir-dsl-fe",
    "crates/nemoir-cli",
    "crates/nemoir-backend-visualizer",
    "crates/nemoir-backend-python",
    "crates/nemoir-backend-web",
    "crates/nemoir-wasm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
