[package]
name = "nemoir-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "nemo"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
miette = { version = "7", features = ["fancy"] }
serde_yaml = "0.9"
nemoir-dsl-fe = { path = "../nemoir-dsl-fe" }
nemoir-ir = { path = "../nemoir-ir" }
nemoir-backend-visualizer = { path = "../nemoir-backend-visualizer" }
nemoir-backend-python = { path = "../nemoir-backend-python" }
nemoir-backend-web = { path = "../nemoir-backend-web" }
